### ISSUE TITLE
Site request 

### ISSUE THREAD

**Issue by AsfandYar1211** [redowan99/Redowan-CloudStream#1]
https://skymovieshd.diy/
Add this ..if possible..

**Comment by redowan99** [comment]
I working on it.

**Comment by AsfandYar1211** [comment]
Thanks for adding..but most of time it gives no link..But links in Google drive works on site..add hubdrive and gdflix links..if possible

**Comment by redowan99** [comment]
Now working. Except image server are slow and image size is big(i can't do anything about it). Because of this plugin fells sluggish. If i turn of images it wouldn't look good. What is your opinion, image off or on?

**Comment by redowan99** [comment]
Now working. Except image server are slow and image size is big(i can't do anything about it). Because of this plugin fells sluggish. If i turn of images it wouldn't look good. What is your opinion, image off or on?

And this isn't a good website to scrape, they don't maintain constancy. They keep changing how they post movies. So, I will no longer work on this website.

**Comment by AsfandYar1211** [comment]
Image off or on  doesn't matter..as long it's working fine..👍
